import asyncio
from PIL import Image
from providers.base import VisionExtractionProvider


class MockVisionProvider(VisionExtractionProvider):
    """Returns a realistic, fully-populated MTO for any image input.

    Used when GOOGLE_API_KEY is not configured. Clearly marked mock=True.
    Based on the XTechs Testings Pvt Ltd sample isometric (CDU-II, Loop-3).
    """

    @property
    def name(self) -> str:
        return "Mock Provider (No API Key)"

    async def extract(self, image: Image.Image) -> dict:
        await asyncio.sleep(1.8)  # Simulate API network delay so UI timeline animation is visible
        return {
            "drawing_meta": {
                "drawing_no": "XPRF-17",
                "revision": "A",
                "line_number": "2\"-P-LOOP3-A1A",
                "nps": "2\"",
                "material_class": "A1A",
                "service": "Process (CDU-II)",
                "design_pressure": "10 kg/cm²",
                "design_temperature": "250°C",
                "sheet_number": "1 of 1",
            },
            "items": [
                {
                    "item_no": 1,
                    "category": "PIPE",
                    "description": "Pipe, Seamless, BE, ASME B36.10",
                    "size_nps": "2\"",
                    "schedule_rating": "SCH 40",
                    "material_spec": "ASTM A106 Gr.B",
                    "end_type": "BW",
                    "quantity": 1,
                    "unit": "M",
                    "length_m": 18.6,
                    "confidence": 0.95,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 2,
                    "category": "PIPE",
                    "description": "Pipe, Seamless, BE, ASME B36.10",
                    "size_nps": "1.5\"",
                    "schedule_rating": "SCH 40",
                    "material_spec": "ASTM A106 Gr.B",
                    "end_type": "BW",
                    "quantity": 1,
                    "unit": "M",
                    "length_m": 6.2,
                    "confidence": 0.93,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 3,
                    "category": "FITTING",
                    "description": "Elbow 90° LR, BW, ASME B16.9",
                    "size_nps": "2\"",
                    "schedule_rating": "SCH 40",
                    "material_spec": "ASTM A234 WPB",
                    "end_type": "BW",
                    "quantity": 8,
                    "unit": "EA",
                    "confidence": 0.91,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 4,
                    "category": "FITTING",
                    "description": "Elbow 45° LR, BW, ASME B16.9",
                    "size_nps": "2\"",
                    "schedule_rating": "SCH 40",
                    "material_spec": "ASTM A234 WPB",
                    "end_type": "BW",
                    "quantity": 3,
                    "unit": "EA",
                    "confidence": 0.88,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 5,
                    "category": "FITTING",
                    "description": "Equal Tee, BW, ASME B16.9",
                    "size_nps": "2\"",
                    "schedule_rating": "SCH 40",
                    "material_spec": "ASTM A234 WPB",
                    "end_type": "BW",
                    "quantity": 4,
                    "unit": "EA",
                    "confidence": 0.87,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 6,
                    "category": "FITTING",
                    "description": "Concentric Reducer, BW, ASME B16.9",
                    "size_nps": "2\"x1.5\"",
                    "schedule_rating": "SCH 40",
                    "material_spec": "ASTM A234 WPB",
                    "end_type": "BW",
                    "quantity": 2,
                    "unit": "EA",
                    "confidence": 0.84,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 7,
                    "category": "FLANGE",
                    "description": "Weld Neck Flange, RF, ASME B16.5",
                    "size_nps": "2\"",
                    "schedule_rating": "CL150",
                    "material_spec": "ASTM A105",
                    "end_type": "BW",
                    "quantity": 6,
                    "unit": "EA",
                    "confidence": 0.89,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 8,
                    "category": "VALVE",
                    "description": "Gate Valve, Flanged, PN16, ASME B16.5",
                    "size_nps": "2\"",
                    "schedule_rating": "CL150",
                    "material_spec": "ASTM A216 WCB",
                    "end_type": "FLGD",
                    "quantity": 3,
                    "unit": "EA",
                    "confidence": 0.92,
                    "remarks": "MOCK DATA",
                },
                {
                    "item_no": 9,
                    "category": "GASKET",
                    "description": "Spiral Wound Gasket, SS316/Graphite, ASME B16.20",
                    "size_nps": "2\"",
                    "schedule_rating": "CL150",
                    "material_spec": "SS316/Graphite",
                    "end_type": "FLGD",
                    "quantity": 6,
                    "unit": "EA",
                    "confidence": 0.95,
                    "remarks": "MOCK DATA — derived from flanged joints",
                },
                {
                    "item_no": 10,
                    "category": "BOLT",
                    "description": "Stud Bolt with 2 Hex Nuts, ASME B18.2.1",
                    "size_nps": "2\"",
                    "schedule_rating": "CL150",
                    "material_spec": "ASTM A193 B7 / A194 2H",
                    "end_type": "FLGD",
                    "quantity": 6,
                    "unit": "SET",
                    "confidence": 0.95,
                    "remarks": "MOCK DATA — 1 set per flanged joint",
                },
                {
                    "item_no": 11,
                    "category": "SUPPORT",
                    "description": "Pipe Shoe Support",
                    "size_nps": "2\"",
                    "schedule_rating": "",
                    "material_spec": "ASTM A36",
                    "end_type": "",
                    "quantity": 4,
                    "unit": "EA",
                    "confidence": 0.78,
                    "remarks": "MOCK DATA — tagged S-NO-3xx on drawing",
                },
            ],
            "summary": {
                "total_pipe_length_m": 24.8,
                "fittings": 17,
                "flanges": 6,
                "valves": 3,
                "gaskets": 6,
                "bolt_sets": 6,
                "supports": 4,
                "field_welds": 2,
            },
        }
